version: '3'
services:
  backend:
    build:
      context: ./backend
    ports:
      - "3500:3500"
    depends_on:
      - mongodb
    environment:
      - DATABASE_URL=mongodb://mongodb:27017  # MongoDB connection URL
    networks:
      - mynetwork

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    networks:
      - mynetwork

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - mynetwork

volumes:
  mongo-data:

networks:
  mynetwork:
